---

- hosts: all
  remote_user: ubuntu

  tasks: 
   - name: Install Tomcat8
     apt:
       update_cache: yes
       name: tomcat8
       state: present
     become: yes
   - name: Dump Artifacts
     copy:
       src: /home/ubuntu/Java_sample_app/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war
       dest: /var/lib/tomcat8/webapps
     become: yes
   - name: Start Tomcat8
     service:
       name: tomcat8

       state: started  

